baseURL = "https://www.vlvrd.me/"
description = "space dojo"
theme = "ananke"
title = "vlvrd"

[Params]
  author = "sergio valverde"
  background_color_class = "bg-black"
  email = "vlvrdv@gmail.com"
  github = "vlvrd"
  gitlab = "vlvrd"
  instagram = "vlvrd"
  spotify = "vlvrdv"
  twitter = "vlvrdv"
