baseURL = "/"
languageCode = "en-us"
title = "vlvrd"
theme = "kube"
description = ""
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "sergio valverde"
  github = "vlvrd"
  instagram = "vlvrd"
  spotify = "vlvrdv"
  twitter = "vlvrdv"
  email = "vlvrdv@gmail.com"

[[menu.main]]
    name = "blog"
    weight = -100
    url = "/blog/"
