BaseURL = "https://www.vlvrd.me/"
description = "space adventure"
enableEmoji = true
theme = "ananke"
title = "vlvrd"

[params]
  author = "sergio valverde"
  background_color_class = "bg-white"
  body_classes = "monaco bg-white"
  custom_css = ["css/_social-icons.css"]
  dev = "vlvrd"
  email = "vlvrdv@gmail.com"
  github = "vlvrd"
  gitlab = "vlvrd"
  instagram = "vlvrd"
  medium = "vlvrd"
  spotify = "vlvrdv"
  twitter = "vlvrdv"
